config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resource :session, only: %i[new create destroy]
  resources :passwords, param: :token, only: %i[new create edit update]

  # Defines the root path route ("/")
  root "events#index"

  resources :venues, only: %i[index show edit update destroy] do
    get :unverified, on: :collection
    patch :verify, on: :member
    post :geocode, on: :member
  end

  resources :events do
    get :unverified, on: :collection
    patch :verify, on: :member
  end

  get :team, to: "sessions#new"
  get :unverified, to: "admin_pages#unverified"

  get :map, to: "events#map"
  get :calendar, to: "events#calendar"

  get :apropos, to: "pages#about", as: :about

  get :contact, to: "pages#contact"
  post :contact, to: "pages#contact_form_submit"

  namespace :api do
    resources :events, only: %i[index show]
    resources :venues, only: %i[index show]
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :zipcode, presence: true
  validates :city, presence: true

  geocoded_by :full_address
  after_commit :geocode_later, on: :create
  before_save :normalize_fields_for_search, if: [:changed?]

  def geocode_later
    GeocodeVenueJob.perform_later(self)
  end

  def full_address
    "#{address}, #{zipcode} #{city}, France"
  end

  def verified? = verified

  def unverified? = !verified

  def possible_duplicates
    sql = <<~SQL
      name LIKE :name
      OR (address LIKE :address AND city LIKE :city)
    SQL
    data_dups = Venue.where(sql, name:, address:, city:)
    location_dups = geocoded? ? nearbys(0.01) : []
    (data_dups + location_dups).uniq
  end

  def possible_duplicate?
    possible_duplicates.count > 1
  end

  def in_region?
    return nil unless geocoded?

    zipcode.start_with?("22", "29", "35", "44", "56")
  end

  def normalize_fields_for_search
    search_fields = "#{name} #{address} #{city}"
    self.normalized_fields = I18n.transliterate(search_fields)
  end

  class << self
    def filter_by_query(query)
      sql = <<~SQL
        venues.name LIKE :string
        OR venues.address LIKE :string
        OR venues.city LIKE :string
      SQL
      Venue.where(sql, string: "%#{query}%")
    end

    def order_by(option)
      case option
      when "created_at" then order(:created_at)
      when "position" then order(:latitude, :longitude)
      else order("name")
      end
    end

    def all_verified
      @venues = Venue.where(verified: true)
    end

    def all_unverified
      @venues = Venue.where(verified: false).order(:created_at)
    end
  end
end

app/controllers/api/venues_controller.rb
class Api::VenuesController < ApplicationController
  allow_unauthenticated_access only: %i[index show]

  VENUE_COLUMNS = %i[id name address zipcode city latitude longitude verified]

  def index
    @venues = Venue.filter_by_query(params[:q])
      .limit(params[:limit])
      .order_by(params[:order])
    @venues = authorize policy_scope(@venues)
    render json: @venues, only: VENUE_COLUMNS
  end

  def show
    @venue = authorize Venue.find(params[:id])
    render json: @venue, only: VENUE_COLUMNS
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  # allow_unauthenticated_access only: %i[]
  before_action :set_venue, only: %i[show edit update verify destroy geocode]

  def index
    @venues = Venue.filter_by_query(params[:q])
      .limit(params[:limit])
      .order_by(params[:order])
    @venues = authorize policy_scope(@venues)
  end

  def unverified
    @venues = authorize Venue.all_unverified
  end

  def show
    render partial: @venue if turbo_frame_request?
  end

  def verify
    @venue.update(verified: true)
    render @venue
  end

  def edit
  end

  def update
    if @venue.update(venue_params)
      redirect_to @venue
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @venue.destroy
  end

  def geocode
    @venue.geocode_later
  end

  private

  def set_venue
    @venue = authorize Venue.find(params[:id])
  end

  def venue_params
    params.expect(venue: [:name, :address, :zipcode, :city])
  end
end

app/helpers/api/venues_helper.rb
module Api::VenuesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.slim
div[
  data-controller="venue-fields"
  data-venue-fields-mode-value=venue_fields_mode(venue)
]
  = fields_for for_params, venue do |venue_fields|

    div.relative.flex.flex-col.gap-2 data-events-form-target="venueFields"

      - if defined? event_fields
        = event_fields.hidden_field :venue_id,
          data: {venue_fields_target: "id"}

      div
        = venue_fields.text_field :name,
          class: "venue-name font-normal w-full #{"border-orange" if event.errors[:venue].present?}",
          placeholder: "Chercher un lieu...",
          data: { action: "focus->venue-fields#onFocus keyup->venue-fields#onVenueInput",
                  venue_fields_target: "name"}

        /clear input icon
        div.hidden.absolute.top-2.right-1[
          data-venue-fields-target="clearInputBtn"
          data-action="click->venue-fields#onClearBtnClick"
          viewBox="0 0 512 512"
          title="Réinitialiser la recherche"
        ]
          svg.h-5.fill-blue-faded.hover:fill-yellow.hover:cursor-pointer viewBox="0 0 512 512"
            path d="M256 48a208 208 0 1 1 0 416 208 208 0 1 1 0-416zm0 464A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM175 175c-9.4 9.4-9.4 24.6 0 33.9l47 47-47 47c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l47-47 47 47c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-47-47 47-47c9.4-9.4 9.4-24.6 0-33.9s-24.6-9.4-33.9 0l-47 47-47-47c-9.4-9.4-24.6-9.4-33.9 0z"

        /search icon
        div.hidden.absolute.top-2.right-1[
            data-venue-fields-target="searchBtn"
            data-action="click->venue-fields#onSearchBtnClick"
            title="Chercher dans la liste"
        ]
          svg.h-5.fill-blue-faded.hover:fill-yellow.hover:cursor-pointer viewBox="0 0 512 512"
            path d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"

        div.hidden.z-40.absolute.top-10.rounded-md.bg-white.border-2.border-yellow[
          data-events-form-target="venueDropdown"
          data-venue-fields-target="dropdown"
        ]
          ul data-venue-fields-target="resultsList"

          template data-venue-fields-target="template"
            li.p-2.font-paragraph.hover:bg-yellow.hover:cursor-pointer[
              data-action="click->venue-fields#onVenueSelect"
            ]
              div.flex.gap-2.items-center
                - if policy(venue).edit?
                  /exclamation icon
                  = link_to unverified_path(section: "venues"), title: "❌ Le lieu n'est pas vérifié", data: {turbo_frame: :_top}
                    svg.h-4.fill-orange viewBox="0 0 512 512": path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zm0-384c13.3 0 24 10.7 24 24l0 112c0 13.3-10.7 24-24 24s-24-10.7-24-24l0-112c0-13.3 10.7-24 24-24zM224 352a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"
                p.venue-name-selector.font-bold.text-lg/5.text-ellipsis.overflow-hidden.whitespace-nowrap
              p.venue-address-selector.text-sm.text-blue-faded.text-ellipsis.overflow-hidden.whitespace-nowrap

          div.p-2.italic.text-center.text-blue-faded.font-paragraph data-venue-fields-target="noResult"
            | Aucun résultat

          hr.border-yellow-faded

          div.p-2.text-center.font-paragraph.hover:bg-yellow.hover:cursor-pointer[
            data-action="click->venue-fields#onAddManually"
          ]
            p.font-bold Ajouter manuellement

      div.flex.flex-col.gap-2.relative
        = venue_fields.text_field :address,
          placeholder: "Adresse",
          data: {venue_fields_target: "address",
            action: "keyup->venue-fields#onAddressInput"}

        div.hidden.z-40.absolute.top-10.rounded-md.bg-white.border-2.border-yellow[
          data-events-form-target="venueDropdown"
          data-venue-fields-target="addressDropdown"
        ]
          ul data-venue-fields-target="addressesList"

          template data-venue-fields-target="addressTemplate"
            li.px-2.py-1.min-w-55.leading-5.font-paragraph.hover:bg-yellow.hover:cursor-pointer.focus:bg-yellow[
              data-action="click->venue-fields#onAddressSelect"
              tabindex=0
            ]
              p.address-first.text-ellipsis.overflow-hidden.whitespace-nowrap
              p.address-last.text-blue-faded.text-ellipsis.overflow-hidden.whitespace-nowrap

        div.flex.gap-2

          = venue_fields.text_field :zipcode,
            maxlength: 5,
            placeholder: "CP",
            data: {venue_fields_target: "zipcode"}

          = venue_fields.text_field :city,
            class: "w-full",
            placeholder: "Ville",
            data: {venue_fields_target: "city"}

app/views/venues/_venue.html.slim
= turbo_frame_tag venue

  article.flex.flex-col.p-2.gap-8.items-center.md:flex-row class=(venue.verified ? "bg-white" : "bg-yellow-faded !text-blue-faded")
    
    - if policy(venue).edit?
      div.flex.flex-row-reverse.gap-8.justify-around.items-center.md:flex-col.md:gap-1
        div.flex.gap-2.basis-8.items-center
          /edit icon
          = link_to edit_venue_path(venue), title: "Modifier le lieu", data: {turbo_frame: dom_id(venue, :edit)}
            svg.h-5.fill-blue-faded.hover:fill-blue viewBox="0 0 512 512": path d="M471.6 21.7c-21.9-21.9-57.3-21.9-79.2 0L362.3 51.7l97.9 97.9 30.1-30.1c21.9-21.9 21.9-57.3 0-79.2L471.6 21.7zm-299.2 220c-6.1 6.1-10.8 13.6-13.5 21.9l-29.6 88.8c-2.9 8.6-.6 18.1 5.8 24.6s15.9 8.7 24.6 5.8l88.8-29.6c8.2-2.7 15.7-7.4 21.9-13.5L437.7 172.3 339.7 74.3 172.4 241.7zM96 64C43 64 0 107 0 160L0 416c0 53 43 96 96 96l256 0c53 0 96-43 96-96l0-96c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 96c0 17.7-14.3 32-32 32L96 448c-17.7 0-32-14.3-32-32l0-256c0-17.7 14.3-32 32-32l96 0c17.7 0 32-14.3 32-32s-14.3-32-32-32L96 64z"
          /trash icon
          = link_to venue_path(venue),
            class: "h-fit",
            title: "❌ Supprimer le lieu",
            data: {turbo_method: :delete, turbo_confirm: "Supprimer ce lieu ?\n#{venue.events.count} événements associés seront supprimés:#{venue.events.map{|e| "#{e.name}"}}"}
            svg.h-4.fill-blue-faded.hover:fill-blue viewBox="0 0 448 512": path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"
          - if venue.unverified?
            /confirm icon
            = link_to verify_venue_path(venue),
              class: "h-fit",
              title: "✅ Valider le lieu",
              data: {turbo_method: :patch}
              svg.h-5.fill-blue-faded.hover:fill-blue viewBox="0 0 512 512": path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM369 209L241 337c-9.4 9.4-24.6 9.4-33.9 0l-64-64c-9.4-9.4-9.4-24.6 0-33.9s24.6-9.4 33.9 0l47 47L335 175c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9z"
        /warnings
        div.flex.gap-2.basis-8
          - if venue.possible_duplicate?
            div title="⚠️ Doublon possible (nom ou proximité)"
              svg.h-5.fill-orange viewBox="0 0 512 512": path d="M288 448L64 448l0-224 64 0 0-64-64 0c-35.3 0-64 28.7-64 64L0 448c0 35.3 28.7 64 64 64l224 0c35.3 0 64-28.7 64-64l0-64-64 0 0 64zm-64-96l224 0c35.3 0 64-28.7 64-64l0-224c0-35.3-28.7-64-64-64L224 0c-35.3 0-64 28.7-64 64l0 224c0 35.3 28.7 64 64 64z"
          - unless venue.geocoded?
              = link_to geocode_venue_path(venue),
                class: "h-fit",
                title: "❌ Pas géocodé. Cliquer pour recalculer les coordonnées à partir de l'adresse",
                data: {turbo_method: :post, turbo_confirm: "Le geocoding est asynchrone: rechargez la page dans quelques secondes pour voir le résultat"}
                svg.h-5.fill-orange viewBox="0 0 640 512": path d="M38.8 5.1C28.4-3.1 13.3-1.2 5.1 9.2S-1.2 34.7 9.2 42.9l592 464c10.4 8.2 25.5 6.3 33.7-4.1s6.3-25.5-4.1-33.7L481.4 352c9.8-.4 18.9-5.3 24.6-13.3c6-8.3 7.7-19.1 4.4-28.8l-1-3c-13.8-41.5-42.8-74.8-79.5-94.7L418.5 64 448 64c17.7 0 32-14.3 32-32s-14.3-32-32-32L192 0c-17.7 0-32 14.3-32 32s14.3 32 32 32l29.5 0-6.1 79.5L38.8 5.1zM324.9 352L177.1 235.6c-20.9 18.9-37.2 43.3-46.5 71.3l-1 3c-3.3 9.8-1.6 20.5 4.4 28.8s15.7 13.3 26 13.3l164.9 0zM288 384l0 96c0 17.7 14.3 32 32 32s32-14.3 32-32l0-96-64 0z"
          - if venue.geocoded? && !venue.in_region?
            div title= "❌ Pas en Bretagne/Loire-Atlantique"
              svg.h-5.fill-orange viewBox="0 0 640 512": path d="M381 114.9L186.1 41.8c-16.7-6.2-35.2-5.3-51.1 2.7L89.1 67.4C78 73 77.2 88.5 87.6 95.2l146.9 94.5L136 240 77.8 214.1c-8.7-3.9-18.8-3.7-27.3 .6L18.3 230.8c-9.3 4.7-11.8 16.8-5 24.7l73.1 85.3c6.1 7.1 15 11.2 24.3 11.2l137.7 0c5 0 9.9-1.2 14.3-3.4L535.6 212.2c46.5-23.3 82.5-63.3 100.8-112C645.9 75 627.2 48 600.2 48l-57.4 0c-20.2 0-40.2 4.8-58.2 14L381 114.9zM0 480c0 17.7 14.3 32 32 32l576 0c17.7 0 32-14.3 32-32s-14.3-32-32-32L32 448c-17.7 0-32 14.3-32 32z"

    div.w-full.text-center class="w-full md:text-left md:basis-[40%]"

      = turbo_frame_tag dom_id(venue, :edit)

        h3.text-xl.font-title = venue.name
        p.font-paragraph.text-blue-faded.italic = venue.address
        p.font-paragraph.text-lg = "#{venue.zipcode} #{venue.city}"

    = link_to "https://www.openstreetmap.org/search?query=#{venue.latitude}%20#{venue.longitude}&zoom=20",
      class: "hover:text-yellow flex items-center gap-2 grow"
      div
        /Location label
        svg.h-5.fill-blue-faded viewBox="0 0 384 512": path d="M215.7 499.2C267 435 384 279.4 384 192C384 86 298 0 192 0S0 86 0 192c0 87.4 117 243 168.3 307.2c12.3 15.3 35.1 15.3 47.4 0zM192 128a64 64 0 1 1 0 128 64 64 0 1 1 0-128z"

      div
        div.flex.flex-row.gap-2.md:flex-col
          p = venue.latitude
          p = venue.longitude
        p.underline Vérifier sur OSM

    div
      |TODO: aperçu map

app/views/venues/destroy.turbo_stream.slim
= turbo_stream.replace @venue do

  p.text-blue-faded.text-center.text-sm
    | Supprimé: (#{@venue.name}, #{@venue.city})

app/views/venues/edit.html.slim
= turbo_frame_tag dom_id(@venue, :edit)

  div.relative.bg-white.p-2.pb-12.text-blue

    = form_with model: @venue do |form|

      div.flex.flex-col.gap-2

        = form.text_field :name,
          class: "venue-name font-normal w-full",
          placeholder: "Chercher un lieu..."

        div.flex.flex-col.gap-2

          = form.text_field :address,
            placeholder: "Adresse"

          div.flex.gap-2

            = form.text_field :zipcode,
              maxlength: 5,
              placeholder: "Code postal"

            = form.text_field :city,
              class: "w-full",
              placeholder: "Ville"

      div.md:absolute.md:right-2.md:bottom-2.flex.gap-1.items-center.justify-center.mt-2
        = link_to "Annuler", @venue, class: "btn"
        = form.submit "OK", class: "btn btn-plain"

app/views/venues/index.html.slim
= turbo_frame_tag :content

  div.flex.mb-12.-mt-20.justify-around.text-sm.underline.font-paragraph.md:-mt-10

    = link_to "Par nom", venues_path(order: :name), class: "hover:text-yellow"
    = link_to "Par date de création", venues_path(order: :created_at), class: "hover:text-yellow"
    = link_to "Par position", venues_path(order: :position), class: "hover:text-yellow"

  section.flex.flex-col.gap-27.overflow-hidden.md:gap-8.md:rounded-lg

    = render @venues

app/views/venues/unverified.html.slim
= turbo_frame_tag :content

  section.flex.flex-col.gap-27.overflow-hidden.md:gap-8.md:rounded-lg

    = render @venues